CREATE TABLE CUSTOMER
(
   CUSTOMER_ID VARCHAR(50),
   CUSTOMER_NAME VARCHAR(50),
   CUSTOMER_AGE NUMBER(3),
   USER_ID VARCHAR(50)  NOT NULL,
   PASSWORD VARCHAR(50) NOT NULL,


  CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)

);